name: Dlint
on: [push, pull_request]

jobs:
  dlint:
    runs-on: ubuntu-latest
    name: Dlint
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main  # Ensures the 'main' branch is checked out
              
    # Run the Dlint action
    - uses: dlint-py/dlint-action@master
